StartUp.WEP/Controllers/UserManagmentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using StartUp.DAL.Database;
using StartUp.DAL.Extend;
using StartUp.BLL.Models.UserDTO;
using StartUp.BLL.Models.StaticData;
using Microsoft.EntityFrameworkCore;

namespace StartUp.WEP.Controllers
{
    [Authorize(Roles = "Admin,Super Admin")]
    public class UserManagmentController : Controller
    {
        #region Prop
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly ApplicationContext db;

        #endregion


        #region Ctor
        public UserManagmentController(UserManager<ApplicationUser> _userManager,
                                        RoleManager<ApplicationRole> _roleManager,
                                        ApplicationContext db)
        {
            this._userManager = _userManager;
            this._roleManager = _roleManager;
            this.db = db;
        }

        #endregion


        #region Action


        [Authorize(Policy = "ViewRolePolicy")]
        public async Task<IActionResult> Index()
        {
            return View();
        }




        [Authorize(Policy = "EditRolePolicy")]
        public async Task<IActionResult> EditUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User With Id = {id} Cannot be found";
                return View("PageNotFound");
            }

            var userClaims = await _userManager.GetClaimsAsync(user);
            var userRoles = await _userManager.GetRolesAsync(user);

            var model = new EditUserDTO
            {
                Id = id,
                Email = user.Email,
                UserName = user.UserName,
                Claims = userClaims.Select(e => e.Type + " : " + e.Value).ToList(),
                Roles = userRoles.ToList()
            };

            return View(model);
        }

        [Authorize(Policy = "EditRolePolicy")]
        [HttpPost]
        public async Task<IActionResult> EditUser(EditUserDTO model)
        {
            var user = await _userManager.FindByIdAsync(model.Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User With Id = {model.Id} Cannot be found";
                return View("PageNotFound");
            }
            else
            {
                user.Email = model.Email;
                user.UserName = model.UserName;

                var result = await _userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View(model);
            }
        }





        [Authorize(Policy = "DeleteRolePolicy")]
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User With Id = {id} Cannot be found";
                return View("PageNotFound");
            }
            var model = new DeleteUserDTO
            {
                Id = id,
                UserName = user.UserName,
                Email = user.Email
            };

            return View(model);
        }


        [Authorize(Policy = "DeleteRolePolicy")]
        [HttpPost]
        public async Task<IActionResult> DeleteUser(EditUserDTO model)
        {
            var user = await _userManager.FindByIdAsync(model.Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User With Id = {model.Id} Cannot be found";
                return View("PageNotFound");
            }
            else
            {

                // Check if the user is associated with any roles
                var roles = await _userManager.GetRolesAsync(user);
                if (roles.Any())
                {
                    // User is associated with roles, cannot delete
                    ViewBag.ErrorTitle = "Error Deleting User";
                    ViewBag.ErrorMessage = "Not able to delete user. Please remove user from role(s) first and try again.";
                    return View("Error");
                }

                // Remove all claims associated with the user
                var claims = await _userManager.GetClaimsAsync(user);
                foreach (var claim in claims)
                {
                    var claimRemovalResult = await _userManager.RemoveClaimAsync(user, claim);
                    if (!claimRemovalResult.Succeeded)
                    {
                        // Handle claim removal failure if necessary
                        ViewBag.ErrorTitle = "Error Deleting User Claims";
                        ViewBag.ErrorMessage = "An error occurred while deleting the user claims.";
                        return View("Error");
                    }
                }

                // Remove any logins associated with the user
                var logins = await _userManager.GetLoginsAsync(user);
                foreach (var login in logins)
                {
                    var loginRemovalResult = await _userManager.RemoveLoginAsync(user, login.LoginProvider, login.ProviderKey);
                    if (!loginRemovalResult.Succeeded)
                    {
                        ViewBag.ErrorTitle = "Error Deleting User";
                        ViewBag.ErrorMessage = "An error occurred while deleting the user logins.";
                        return View("Error");
                    }
                }


                // Proceed with user deletion
                var deletionResult = await _userManager.DeleteAsync(user);

                if (deletionResult.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in deletionResult.Errors)
                {
                    ViewBag.ErrorTitle = "Error Deleting User";
                    ViewBag.ErrorMessage = "An error occurred while deleting the user.";
                    ModelState.AddModelError("", error.Description);
                }
                return View(model);
            }
        }








        public async Task<IActionResult> ManageUserRoles(string userId)
        {
            ViewBag.userId = userId;

            var user = await _userManager.FindByIdAsync(userId);
            ViewBag.userName = user.UserName;

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User With Id = {userId} Cannot be found";
                return View("PageNotFound");
            }

            var model = new List<UserRolesDTO>();

            foreach (var role in _roleManager.Roles)
            {
                var userRolesDTO = new UserRolesDTO
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesDTO.IsSelected = true;
                }
                else
                {
                    userRolesDTO.IsSelected = false;
                }

                model.Add(userRolesDTO);
            }

            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> ManageUserRoles(List<UserRolesDTO> model, string userId)
        {
            var user = await _userManager.FindByIdAsync(userId);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found.";
                return View("PageNotFound");
            }

            var roles = await _userManager.GetRolesAsync(user);
            var result = await _userManager.RemoveFromRolesAsync(user, roles);

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot Remove User Existing Roles.");
                return View(model);
            }

            result = await _userManager.AddToRolesAsync(user, model.Where(x => x.IsSelected).Select(y => y.RoleName));
            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot Add The Selected Roles To User.");
                return View(model);
            }


            return RedirectToAction("EditUser", new { Id = userId });
        }




        public async Task<IActionResult> ManageUserClaims(string userId)
        {
            ViewBag.userId = userId;

            var user = await _userManager.FindByIdAsync(userId);

            ViewBag.userName = user.UserName;

            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("PageNotFound");
            }

            var existingUserClaims = await _userManager.GetClaimsAsync(user);
            var model = new UserClaimsDTO
            {
                UserId = userId
            };

            foreach (Claim claim in ClaimsStore.AllClaims)
            {
                UserClaim userClaim = new UserClaim
                {
                    ClaimType = claim.Type
                };

                if (existingUserClaims.Any(c => c.Type == claim.Type && c.Value == "true"))
                {
                    userClaim.IsSelected = true;
                }
                model.Claims.Add(userClaim);
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ManageUserClaims(UserClaimsDTO model)
        {

StartUp.WEP/Views/UserManagment/DeleteUser.cshtml
@model DeleteUserDTO

@{
    ViewData["Title"] = "DeleteUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0"> Delete User </h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active">Delete User</li>
                    <li class="breadcrumb-item"><a asp-controller="UserManagment" asp-action="index">User Managment</a></li>
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="index"><i class="fas fa-home col-sm-2"></i></a></li>

                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div>
</div>

<!-- Horizontal Form -->
<div>

    <div class="card card-secondary w-50 m-auto">
        <div class="card-header">
            <h3 class="card-title">Delete User</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="card-body">
                <div class="form-group row">
                    <label asp-for="Id" class="col-sm-2 col-form-label">User Id </label>
                    <input class="form-control col-sm-10" asp-for="Id" disabled>
                </div>
                <div class="form-group row">
                    <label asp-for="Email" class="col-sm-2 col-form-label">User Email</label>
                    <input class="form-control col-sm-10" asp-for="Email" disabled>
                </div>
            </div>
            <!-- /.card-body -->



            <div class="card-footer">
                <button type="submit" class="btn btn-danger"
                        onclick="return confirm('Are You Sure You Want To Delete User : @Model.UserName ? ')">
                    Delete User
                </button>
                <a class="btn btn-primary" asp-action="EditUser" asp-route-id="@Model.Id"> Edit User </a>
                <a class="btn btn-secondary float-right" asp-action="Index"> Back </a>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
    <!-- /.card -->

</div>

StartUp.WEP/Views/UserManagment/EditUser.cshtml
@model EditUserDTO


@{
    ViewData["Title"] = "EditUser";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0"> Edit User </h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active">Edit User</li>
                    <li class="breadcrumb-item"><a asp-controller="UserManagment" asp-action="index">User Managment</a></li>
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="index"><i class="fas fa-home col-sm-2"></i></a></li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div>
</div>

<!-- Horizontal Form -->
<div>

    <div class="card card-secondary w-50 m-auto">
        <div class="card-header">
            <h3 class="card-title">Edit User</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="card-body">
                <div class="form-group row">
                    <label asp-for="Id" class="col-sm-2 col-form-label">User Id </label>
                    <input class="form-control col-sm-10" asp-for="Id" disabled>
                </div>
                <div class="form-group row">
                    <label asp-for="Email" class="col-sm-2 col-form-label">User Email</label>
                    <input class="form-control col-sm-10" asp-for="Email">
                </div>
                <div class="form-group row">
                    <label asp-for="UserName" class="col-sm-2 col-form-label">User Name</label>
                    <input class="form-control col-sm-10" asp-for="UserName">
                </div>
            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary"> Edit User </button>
                <a class="btn btn-danger" asp-action="DeleteUser" asp-route-id="@Model.Id"> Delete User </a>
                <a class="btn btn-secondary float-right" asp-action="Index"> Back </a>
            </div>
            <!-- /.card-footer -->


            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">Edit Roles</h3>
                </div>
                <div class="card-body">
                    @if (Model.Roles.Any())
                    {
                        foreach (var role in Model.Roles)
                        {
                                    <h5 class="card-title">@role</h5>
                                    <br />
                        }
                    }
                    else
                    {
                            <h5 class="card-title">No Roles Added Yet</h5>
                    }

                </div>
                <div class="card-footer">
                    <a asp-action="ManageUserRoles" asp-route-userId="@Model.Id" class="btn btn-primary"> Manage Roles </a>
                </div>
            </div>



            <div class="card card-secondary">
                <div class="card-header">
                    <h3 class="card-title">User Claims</h3>
                </div>
                <div class="card-body">
                    @if (Model.Claims.Any())
                    {
                        foreach (var claim in Model.Claims)
                        {
                            @*                         <h5 class="card-title w-25">@claim</h5>
                    <br /> *@
                            if (claim.Contains("true"))
                            {
                                            <h5 class="card-title text-success w-25">@claim</h5>
                                            <br />
                            }
                            else
                            {
                                            <h5 class="card-title text-danger w-25">@claim</h5>
                                            <br />
                            }

                        }
                    }
                    else
                    {
                            <h5 class="card-title">No Claim Added Yet</h5>
                    }

                </div>
                <div class="card-footer">
                    <a asp-action="ManageUserClaims" asp-route-userId="@Model.Id" class="btn btn-primary"> Manage Claims </a>
                </div>
            </div>
        </form>
    </div>
    <!-- /.card -->

</div>

StartUp.WEP/Views/UserManagment/Index.cshtml
@model IEnumerable<ApplicationUser>
@inject IAuthorizationService authorizationService

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section DataTableCss {
        <!-- DataTables -->
        <link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
        <link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
        <link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="~/plugins/datatables-fixedheader/css/fixedheader.bootstrap4.min.css" rel="stylesheet" />
        <link href="~/plugins/datatables-fixedcolumns/css/fixedcolumns.bootstrap4.min.css" rel="stylesheet" />
        <link href="~/datatablestyle/stylesheet.css" rel="stylesheet" />
}


<div class="content-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <h1 class="m-0"> User Management </h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active">User Managment</li>
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="index"><i class="fas fa-home col-sm-2"></i></a></li>

                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div>
</div>

@if ((await authorizationService.AuthorizeAsync(User, "CreateRolePolicy")).Succeeded)
{
    <div class="pl-3 pb-2">
        <a type="btn" asp-controller="Account" asp-action="Register" class="btn btn-primary">Create User</a>
    </div>
}

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-body">
                        <div class="table-responsive">
                            <table id="UserTable" class="table table-bordered table-striped text-center w-100">
                                <thead>
                                    <tr>
                                        <th> User Name </th>
                                        <th> Email </th>
                                        <th> EmailConfirmed </th>
                                        <th> CreatedOn </th>
                                        <th style="width:8%;">Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
            <!-- /.card -->
            </div>
        </div>
    </div>
</section>



<div class="modal fade" id="resetPasswordModal" tabindex="-1" role="dialog" aria-labelledby="resetPasswordModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="resetPasswordModalLabel">Reset Password</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="resetPasswordForm">
                    <input type="hidden" id="resetUserId" />
                    <div class="form-group">
                        <label for="newPassword">New Password</label>
                        <input type="password" class="form-control" id="newPassword" placeholder="Enter new password" required />
                    </div>
                    <div class="form-group">
                        <label for="confirmPassword">Confirm Password</label>
                        <input type="password" class="form-control" id="confirmPassword" placeholder="Confirm new password" required />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" id="savePasswordBtn">Save</button>
            </div>
        </div>
    </div>
</div>


@section DataTableJs {
        <!-- DataTables  & Plugins -->
        <script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
        <script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
        <script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
        <script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
        <script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
        <script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
        <script src="~/plugins/jszip/jszip.min.js"></script>
        <script src="~/plugins/pdfmake/pdfmake.min.js"></script>
        <script src="~/plugins/pdfmake/vfs_fonts.js"></script>
        <script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
        <script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
        <script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
        <script src="~/plugins/datatables-fixedheader/js/datatables.fixedheader.min.js"></script>
        <script src="~/plugins/datatables-fixedcolumns/js/datatables.fixedcolumns.min.js"></script>
        <script src="~/customjs/UserScript.js"></script>

}

StartUp.WEP/Views/UserManagment/ManageUserClaims.cshtml
@model UserClaimsDTO


@{
    ViewData["Title"] = "ManageUserClaims";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userId = ViewBag.userId;
    var userName = ViewBag.userName;
}

<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0"> Edit User Claims </h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active">Edit User Claims </li>
                    <li class="breadcrumb-item"><a asp-controller="UserManagment" asp-action="EditUser" asp-route-Id="@userId">Edit User </a></li>
                    <li class="breadcrumb-item"><a asp-controller="UserManagment" asp-action="index">User Managment</a></li>
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="index"><i class="fas fa-home col-sm-2"></i></a></li>

                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div>
</div>

<!-- Horizontal Form -->
<div>

    <div class="card card-secondary w-50 m-auto">
        <div class="card-header">
            <h3 class="card-title">Edit : @userName.  Claims </h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="card-body">
                @for (int i = 0; i < Model.Claims.Count; i++)
                {
                    <div class="form-check m-1">
                        <input type="hidden" asp-for="@Model.Claims[i].ClaimType" />
                        <input asp-for="@Model.Claims[i].IsSelected" class="form-check-input" />
                        <label asp-for="@Model.Claims[i].IsSelected" class="from-check-label">
                            @Model.Claims[i].ClaimType
                        </label>
                    </div>
                }



            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary"> Update </button>
                <a class="btn btn-secondary float-right" asp-action="EditUser" asp-route-Id="@userId"> Back </a>
            </div>
            <!-- /.card-footer -->

        </form>
    </div>
    <!-- /.card -->

</div>

StartUp.WEP/Views/UserManagment/ManageUserRoles.cshtml
@model List<UserRolesDTO>


@{
    ViewData["Title"] = "ManageUserRoles";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var userId = ViewBag.userId;
    var userName = ViewBag.userName;
}


<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0"> Edit User Roles </h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item active">Edit User Roles </li>
                    <li class="breadcrumb-item"><a asp-controller="UserManagment" asp-action="EditUser" asp-route-Id="@userId">Edit User </a></li>
                    <li class="breadcrumb-item"><a asp-controller="UserManagment" asp-action="index">User Managment</a></li>
                    <li class="breadcrumb-item"><a asp-controller="Home" asp-action="index"><i class="fas fa-home col-sm-2"></i></a></li>

                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div>
</div>

<!-- Horizontal Form -->
<div>

    <div class="card card-secondary w-50 m-auto">
        <div class="card-header">
            <h3 class="card-title">Edit : @userName.  Roles </h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="card-body">

                @for (int i = 0; i < Model.Count; i++)
                {
                        <div class="form-check m-1">
                            <input type="hidden" asp-for="@Model[i].RoleId">
                            <input type="hidden" asp-for="@Model[i].RoleName">
                            <input class="form-check-input" asp-for="@Model[i].IsSelected">
                            <label class="form-check-label" asp-for="@Model[i].IsSelected">
                            @Model[i].RoleName
                            </label>

                        </div>
                }

            </div>
            <!-- /.card-body -->



            <div class="card-footer">
                <button type="submit" class="btn btn-primary"> Update </button>
                <a class="btn btn-secondary float-right" asp-action="EditUser" asp-route-Id="@userId"> Back </a>
            </div>
            <!-- /.card-footer -->

        </form>
    </div>
    <!-- /.card -->

</div>