StartUp.WEP/Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;
using StartUp.BLL.Services;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System;
using System.Threading.Tasks;

namespace StartUp.WEP.Controllers
{
    public class FileController : Controller
    {
        private readonly IFileStorageService _fileStorageService;

        public FileController(IFileStorageService fileStorageService)
        {
            _fileStorageService = fileStorageService;
        }

        // GET: File/Upload
        public IActionResult Upload()
        {
            return View();
        }

        // POST: File/UploadFiles
        [HttpPost("upload")]
        public async Task<IActionResult> UploadFiles(List<IFormFile> files)
        {
            try
            {
                // Validate that files are selected
                if (files == null || files.Count == 0)
                {
                    return BadRequest("No files selected for upload.");
                }

                // Upload files using FileStorageService
                var fileNames = await _fileStorageService.UploadFilesAsync(files);

                // Return success with the file names
                return Ok(new { FileNames = fileNames });
            }
            catch (Exception ex)
            {
                // Return error if exception occurs
                return BadRequest(new { Message = ex.Message });
            }
        }

        // GET: File/Download/{fileName}
        [HttpGet("download/{fileName}")]
        public async Task<IActionResult> DownloadFile(string fileName)
        {
            try
            {
                // Call the DownloadFile method from the service
                var fileStream = await _fileStorageService.DownloadFileAsync(fileName);

                // Return the file for download
                return fileStream;
            }
            catch (Exception ex)
            {
                // Return error if file is not found
                return NotFound(new { Message = ex.Message });
            }
        }
    }
}

StartUp.WEP/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace StartUp.WEP.Controllers
{
    public class LanguageController : Controller
    {
        [AllowAnonymous]
        [HttpGet]
        public IActionResult SetLanguage(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

StartUp.WEP/Controllers/RoleManagmentController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StartUp.BLL.Models.RoleDTO;
using StartUp.DAL.Database;
using StartUp.DAL.Extend;

namespace StartUp.WEP.Controllers
{
    public class RoleManagmentController : Controller
    {
        #region Prop
        private readonly RoleManager<ApplicationRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IMapper _mapper;
        private readonly ILogger<RoleManagmentController> logger;
        private readonly ApplicationContext db;

        #endregion

        #region Ctor
        public RoleManagmentController(RoleManager<ApplicationRole> _roleManager,
                                       UserManager<ApplicationUser> _userManager,
                                       IMapper _Mapper,
                                       ILogger<RoleManagmentController> logger,
                                       ApplicationContext db)
        {
            this._roleManager = _roleManager;
            this._userManager = _userManager;
            this._mapper = _Mapper;
            this.logger = logger;
            this.db = db;
        }

        #endregion

        #region Actions 
        [Authorize(Policy = "ViewRolePolicy")]
        public IActionResult Index()
        {
            return View();
        }



        [Authorize(Policy = "CreateRolePolicy")]
        public IActionResult CreateRole()
        {
            return View();
        }


        [Authorize(Policy = "CreateRolePolicy")]
        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleDTO model)
        {
            if (ModelState.IsValid)
            {
                var role = _mapper.Map<ApplicationRole>(model);
                var result = await _roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
            return View(model);
        }




        [Authorize(Policy = "EditRolePolicy")]
        [HttpGet]
        public async Task<IActionResult> EditRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role With Id = {id} Cannot be found";
                return View("PageNotFound");
            }

            //var model = _mapper.Map<ApplicationRole>(role);
            var model = new EditRoleDTO
            {
                Id = role.Id,
                RoleName = role.Name,
                IsExternal = role.IsExternal
            };


            foreach (var user in _userManager.Users)
            {
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    model.Users.Add(user.UserName);
                }
            }

            return View(model);
        }


        [Authorize(Policy = "EditRolePolicy")]
        [HttpPost]
        public async Task<IActionResult> EditRole(EditRoleDTO model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role With Id = {model.Id} Cannot be found";
                return View("PageNotFound");
            }
            else
            {
                role.Name = model.RoleName;
                role.IsExternal = model.IsExternal;
                var result = await _roleManager.UpdateAsync(role);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
                return View(model);
            }
        }




        [Authorize(Policy = "EditRolePolicy")]
        [HttpGet]
        public async Task<IActionResult> EditUserInRole(string RoleId)
        {
            ViewBag.roleId = RoleId;

            var role = await _roleManager.FindByIdAsync(RoleId);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role With Id = {RoleId} Connot be found";
                return View("PageNotFound");
            }

            var model = new List<UserRoleDTO>();

            foreach (var user in _userManager.Users)
            {
                var UserRoleDTO = new UserRoleDTO
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };

                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    UserRoleDTO.IsSelected = true;
                }
                else
                {
                    UserRoleDTO.IsSelected = false;
                }
                model.Add(UserRoleDTO);
            }
            return View(model);
        }

        [Authorize(Policy = "EditRolePolicy")]
        [HttpPost]
        public async Task<IActionResult> EditUserInRole(List<UserRoleDTO> model, string RoleId)
        {
            var role = await _roleManager.FindByIdAsync(RoleId);

            if (role == null)
            {

                ViewBag.ErrorMessage = $"Role With Id = {RoleId} Cannot be found";
                return View("PageNotFound");
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await _userManager.FindByIdAsync(model[i].UserId);

                IdentityResult result = null;

                if (model[i].IsSelected && !(await _userManager.IsInRoleAsync(user, role.Name)))
                {
                    result = await _userManager.AddToRoleAsync(user, role.Name);
                }
                else if (!model[i].IsSelected && await _userManager.IsInRoleAsync(user, role.Name))
                {
                    result = await _userManager.RemoveFromRoleAsync(user, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { Id = RoleId });
                }
            }

            return RedirectToAction("EditRole", new { Id = RoleId });
        }

        //[Authorize(Policy = "EditRolePolicy")]
        //public IActionResult AssignRolesToController()
        //{
        //    // Get controllers from the enum
        //    ViewBag.Controllers = Enum.GetValues(typeof(ControllerNames))
        //        .Cast<ControllerNames>()
        //        .Select(c => new SelectListItem
        //        {
        //            Value = c.ToString(),
        //            Text = c.ToString()
        //        }).ToList();

        //    // Get roles from the database
        //    ViewBag.Roles = _roleManager.Roles
        //        .Select(r => new SelectListItem
        //        {
        //            Value = r.Name,
        //            Text = r.Name
        //        }).ToList();

        //    return View();
        //}


        //[HttpPost]
        //[Authorize(Policy = "EditRolePolicy")]
        //public async Task<IActionResult> AssignRolesToController(string controllerName, List<string> roleNames)
        //{
        //    if (controllerName != null && roleNames != null && roleNames.Any())
        //    {
        //        foreach (var roleName in roleNames)
        //        {
        //            var roleControllerAccess = new RoleControllerAccess
        //            {
        //                ControllerName = controllerName,
        //                RoleName = roleName
        //            };

        //            // Add to the RoleControllerAccess table
        //            await db.RoleControllerAccesses.AddAsync(roleControllerAccess);
        //        }

        //        // Save changes to the database
        //        await db.SaveChangesAsync();

        //        return RedirectToAction("Index");  // Redirect to a page with all roles and controllers
        //    }

        //    ModelState.AddModelError("", "Please select a controller and at least one role.");
        //    return View();
        //}




















        [Authorize(Policy = "DeleteRolePolicy")]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await _roleManager.FindByIdAsync(id);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role With Id = {id} Cannot be found";
                return View("PageNotFound");
            }

            var model = new DeleteRoleDTO
            {
                Id = id,
                RoleName = role.Name,
            };

            return View(model);
        }

        [Authorize(Policy = "DeleteRolePolicy")]
        [HttpPost]
        public async Task<IActionResult> DeleteRole(DeleteRoleDTO model)
        {
            var role = await _roleManager.FindByIdAsync(model.Id);

            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role With Id = {model.Id} Cannot be found";
                return View("PageNotFound");
            }
            else
            {
                try
                {

                    // user.IsDeleted = true; 
                    var result = await _roleManager.DeleteAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }

                    foreach (var error in result.Errors)

StartUp.WEP/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;

@{
    @inject SignInManager<ApplicationUser> _signInManager;

}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Material Request</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- JQVMap -->
    <link rel="stylesheet" href="~/plugins/jqvmap/jqvmap.min.css">


    @RenderSection("DataTableCss", false)


    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="~/plugins/daterangepicker/daterangepicker.css">
    <!-- summernote -->
    <link rel="stylesheet" href="~/plugins/summernote/summernote-bs4.min.css">

    <!-- Include Toastr CSS -->
    @* <link href="~/toastr.js/toastr.css" rel="stylesheet" /> *@
    <link href="~/toastr.js/toastr.min.css" rel="stylesheet" />


    <script>
        // Check if TempData has an error message and show it in a toast
        @if (TempData["ErrorMessage"] != null)
        {
            <text>
                    toastr.error('@TempData["ErrorMessage"]', 'Error');
            </text>
        }
        @if (TempData["SuccessMessage"] != null)
        {
            <text>
                    toastr.success('@TempData["SuccessMessage"]', 'Success');
            </text>
        }
    </script>
</head>
<body class="hold-transition sidebar-mini sidebar-collapse">

    <div class="wrapper">

        <!-- Preloader -->
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="~/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
        </div>


        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button" onclick="adjustScrollHeadWidth()"><i class="fas fa-bars"></i></a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">

                <!-- Logout / change password-->
                @*                 <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-user-circle"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <form asp-controller="Account" asp-action="LogOff" asp-route-returnUrl="@ViewData["ReturnUrl"]" method="post">
                <input type="submit" class="dropdown-item" value="Sign Out" />
                </form>
                </div>
                </li> *@

                @*                 <li class="nav-item">
                    <a asp-controller="Supplier" asp-action="Index" class="nav-link"> @SharedLocalizer["BecomeSupplier"] </a>
                </li> *@


                @if (_signInManager.IsSignedIn(User))
                {


                    <div class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="far fa-user-circle"></i>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenu2">

                            <button class="dropdown-item" type="button">
                                <a asp-controller="Account" asp-action="ChangePassword">
                                    Change Password
                                </a>
                            </button>

                            <form method="post" asp-controller="Account" asp-action="Logoff" asp-route-returnUrl="@ViewData["ReturnUrl"]">
                                <button class="dropdown-item" type="submit">
                                    Logout
                                </button>
                            </form>
                        </div>
                    </div>

                }
                else
                {
                    <li class="nav-item d-none d-sm-inline-block">
                        <a asp-controller="Account" asp-action="Login" class="nav-link"> @SharedLocalizer["Login"] </a>
                    </li>
                }




                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fas fa-language"></i>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="languageDropdown">


                        <a class="dropdown-item d-flex justify-content-between"
                           href="@Url.Action("SetLanguage", "Language", new {
                                                  culture = "en-US",
                                                  returnUrl = Context.Request.Path + Context.Request.QueryString
                                              })">
                            <img src="~/CountriesIcon/usa.png" width="20" height="20" class="mt-1" />
                            <span>@SharedLocalizer["Language-en"]</span>
                        </a>

                        <a class="dropdown-item d-flex justify-content-between"
                           href="@Url.Action("SetLanguage", "Language", new {
                                                  culture = "ar-EG",
                                                  returnUrl = Context.Request.Path + Context.Request.QueryString
                                              })">
                            <img src="~/CountriesIcon/Egypt.png" width="20" height="20" class="mt-1" />
                            <span>@SharedLocalizer["Language-ar"]</span>
                        </a>

                    </div>
                </li>

            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a asp-controller="Home" asp-action="Index" class="brand-link">
                <img src="~/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">ٍMatrial Request</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                @if (_signInManager.IsSignedIn(User) == true)
                {
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                            <img src="~/dist/img/userLogoo2.png" class="img-circle elevation-2" alt="User Image">
                        </div>
                        <div class="info">
                            <a href="#" class="d-block">@User.Identity.Name</a>
                        </div>
                    </div>
                }


                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                             with font-awesome or any other icon font library -->
                        @if (_signInManager.IsSignedIn(User) && User.IsInRole("Admin") || User.IsInRole("Super Admin"))
                        {
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="fas fa-tasks col-sm-2"></i>
                                    <p>
                                        @SharedLocalizer["Management"]
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a asp-controller="UserManagment" asp-action="Index" class="nav-link">
                                            <i class="fas fa-users col-sm-2"></i>
                                            <p>@SharedLocalizer["Users"]</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-controller="RoleManagment" asp-action="Index" class="nav-link">
                                            <i class="fab fa-critical-role col-sm-2"></i>
                                            <p>@SharedLocalizer["Roles"]</p>
                                        </a>
                                    </li>
                                    @*                                     <li class="nav-item">
                                        <a asp-controller="RoleManagment" asp-action="AssignRolesToController" class="nav-link">
                                            <i class="fab fa-critical-role col-sm-2"></i>
                                            <p>@SharedLocalizer["ControllerRoles"]</p>
                                        </a>
                                    </li> *@
                                </ul>
                            </li>
                        }


                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <div class="content-wrapper">
            <!-- Main content -->
            @RenderBody()

            <!-- /.content -->
        </div>

    </div>


    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery Validation-->
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <!-- jQuery UI 1.11.4 -->
    <script src="~/plugins/jquery-ui/jquery-ui.min.js"></script>

    @RenderSection("JQueryValidation", false)

    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>




    <!-- ChartJS -->
    <script src="~/plugins/chart.js/Chart.min.js"></script>
    <!-- Sparkline -->
    <script src="~/plugins/sparklines/sparkline.js"></script>
    <!-- JQVMap -->
    <script src="~/plugins/jqvmap/jquery.vmap.min.js"></script>
    <script src="~/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
    <!-- jQuery Knob Chart -->
    <script src="~/plugins/jquery-knob/jquery.knob.min.js"></script>
    <!-- daterangepicker -->
    <script src="~/plugins/moment/moment.min.js"></script>
    <script src="~/plugins/daterangepicker/daterangepicker.js"></script>
    <!-- Tempusdominus Bootstrap 4 -->
    <script src="~/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
    <!-- Summernote -->
    <script src="~/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.js"></script>

    @RenderSection("DataTableJs", false)

    <!-- Include Toastr JS -->
    <script src="~/toastr.js/toastr.min.js"></script>
    <script src="~/customjs/toastrconfig.js"></script>

    <!-- AdminLTE for demo purposes -->
    @*     <script src="~/dist/js/demo.js"></script> *@
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/dist/js/pages/dashboard.js"></script>

</body>
</html>

StartUp.WEP/Views/Shared/_UploadPartial.cshtml
@* Views/Shared/_UploadPartial.cshtml *@
<div class="modal fade" id="fileUploadModal" tabindex="-1" aria-labelledby="fileUploadModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="fileUploadModalLabel">Upload Files</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="fileUploadForm" enctype="multipart/form-data">
                    <div class="mb-3">
                        <label for="fileInput" class="form-label">Choose files</label>
                        <input class="form-control" type="file" id="fileInput" name="files" multiple>
                    </div>
                </form>
                <ul id="fileList" class="list-group mt-3"></ul> <!-- Display selected files -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="uploadBtn">Upload</button>
            </div>
        </div>
    </div>
</div>

<script>
    // Store the selected files
    let selectedFiles = [];

    // Handle file selection
    document.getElementById('fileInput').addEventListener('change', function () {
        const files = this.files;
        for (let i = 0; i < files.length; i++) {
            if (!selectedFiles.some(file => file.name === files[i].name)) {
                selectedFiles.push(files[i]);
            }
        }
        updateFileList();
    });

    // Update the displayed list of files
    function updateFileList() {
        const fileListElement = document.getElementById('fileList');
        fileListElement.innerHTML = ''; // Clear current list
        selectedFiles.forEach(file => {
            const listItem = document.createElement('li');
            listItem.className = 'list-group-item';
            listItem.textContent = file.name;
            fileListElement.appendChild(listItem);
        });
    }

    // Handle file upload
    document.getElementById('uploadBtn').addEventListener('click', function () {
        if (selectedFiles.length > 0) {
            const formData = new FormData();
            selectedFiles.forEach(file => formData.append("files", file));

            fetch('@Url.Action("UploadFiles", "File")', {
                method: 'POST',
                body: formData,
            })
                .then(response => response.json())
                .then(data => {
                    // alert('Files uploaded successfully');
                    console.log(data);

                    // Close the modal after successful upload
                    const modalElement = document.getElementById('fileUploadModal');
                    const modal = new bootstrap.Modal(modalElement); // Ensure modal is properly initialized
                    modal.hide(); // Hide the modal

                    // Optionally clear the selected files list and update the UI
                    selectedFiles = [];
                    updateFileList();

                    // Optionally reset the file input field
                    document.getElementById('fileInput').value = '';
                })
                .catch(error => {
                    console.error('Error uploading files:', error);
                    alert('Error uploading files. Please try again.');
                });
        } else {
            alert('No files selected.');
        }
    });
</script>

StartUp.WEP/Views/Shared/__Account_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Material Request</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">



    @RenderBody()



    <!-- jQuery -->
    <script src="~/plugins/jquery/jquery.min.js"></script>
    <!-- jQuery Validation-->
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/dist/js/adminlte.min.js"></script>
</body>
</html>